runtime: python
api_version: 1
threadsafe: true
# runtime: python
env: flex
entrypoint: python app.py

runtime_config:
    python_version: 3

# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: main.app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app
