runtime: python
api_version: 1
threadsafe: true
# runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: main.app

handlers:
- url: /api
  script: main.app
- url: /.*
  static_dir: app/build
  secure: always
